create type "public"."exception_type" as enum ('REDUCED', 'EXEMPT');

create type "public"."invite_status" as enum ('pending', 'accepted', 'declined', 'cancelled');

create sequence "public"."categories_id_seq";

create sequence "public"."exceptions_id_seq";

create sequence "public"."expenses_id_seq";

create sequence "public"."households_id_seq";

create sequence "public"."user_expenses_id_seq";

create sequence "public"."users_id_seq";


  create table "public"."categories" (
    "id" integer not null default nextval('public.categories_id_seq'::regclass),
    "name" character varying(100) not null,
    "household_id" integer not null
      );



  create table "public"."exceptions" (
    "id" integer not null default nextval('public.exceptions_id_seq'::regclass),
    "user_id" integer not null,
    "category_id" integer not null,
    "exception_type" public.exception_type not null,
    "percent" numeric(5,2),
    "household_id" integer
      );



  create table "public"."expenses" (
    "id" integer not null default nextval('public.expenses_id_seq'::regclass),
    "household_id" integer not null,
    "category_id" integer not null,
    "description" character varying(255),
    "total_amount" numeric(10,2) not null,
    "expense_date" date default CURRENT_DATE
      );



  create table "public"."household_invites" (
    "id" integer generated by default as identity not null,
    "household_id" integer not null,
    "invited_phone_e164" text not null,
    "inviter_user_ids" integer[] not null default '{}'::integer[],
    "status" public.invite_status not null default 'pending'::public.invite_status,
    "decline_message" text,
    "created_at" timestamp with time zone not null default now(),
    "responded_at" timestamp with time zone
      );



  create table "public"."households" (
    "id" integer not null default nextval('public.households_id_seq'::regclass),
    "name" character varying(100) not null
      );



  create table "public"."user_expenses" (
    "id" integer not null default nextval('public.user_expenses_id_seq'::regclass),
    "expense_id" integer not null,
    "user_id" integer not null,
    "amount_paid" numeric(10,2)
      );



  create table "public"."users" (
    "id" integer not null default nextval('public.users_id_seq'::regclass),
    "household_id" integer not null,
    "display_name" character varying(100) not null,
    "email" character varying(255),
    "monthly_income" numeric(10,2),
    "auth_user_id" uuid,
    "phone_e164" text,
    "onesignal_player_id" text,
    "country_code" text
      );


alter sequence "public"."categories_id_seq" owned by "public"."categories"."id";

alter sequence "public"."exceptions_id_seq" owned by "public"."exceptions"."id";

alter sequence "public"."expenses_id_seq" owned by "public"."expenses"."id";

alter sequence "public"."households_id_seq" owned by "public"."households"."id";

alter sequence "public"."user_expenses_id_seq" owned by "public"."user_expenses"."id";

alter sequence "public"."users_id_seq" owned by "public"."users"."id";

CREATE UNIQUE INDEX categories_name_key ON public.categories USING btree (name);

CREATE UNIQUE INDEX categories_pkey ON public.categories USING btree (id);

CREATE UNIQUE INDEX exceptions_pkey ON public.exceptions USING btree (id);

CREATE UNIQUE INDEX expenses_pkey ON public.expenses USING btree (id);

CREATE INDEX household_invites_phone_status ON public.household_invites USING btree (invited_phone_e164, status);

CREATE UNIQUE INDEX household_invites_pkey ON public.household_invites USING btree (id);

CREATE UNIQUE INDEX household_invites_unique_phone ON public.household_invites USING btree (household_id, invited_phone_e164);

CREATE UNIQUE INDEX households_pkey ON public.households USING btree (id);

CREATE UNIQUE INDEX user_expenses_pkey ON public.user_expenses USING btree (id);

CREATE UNIQUE INDEX users_auth_user_id_key ON public.users USING btree (auth_user_id);

CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);

CREATE UNIQUE INDEX users_phone_e164_key ON public.users USING btree (phone_e164);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."categories" add constraint "categories_pkey" PRIMARY KEY using index "categories_pkey";

alter table "public"."exceptions" add constraint "exceptions_pkey" PRIMARY KEY using index "exceptions_pkey";

alter table "public"."expenses" add constraint "expenses_pkey" PRIMARY KEY using index "expenses_pkey";

alter table "public"."household_invites" add constraint "household_invites_pkey" PRIMARY KEY using index "household_invites_pkey";

alter table "public"."households" add constraint "households_pkey" PRIMARY KEY using index "households_pkey";

alter table "public"."user_expenses" add constraint "user_expenses_pkey" PRIMARY KEY using index "user_expenses_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."categories" add constraint "categories_household_id_fkey" FOREIGN KEY (household_id) REFERENCES public.households(id) not valid;

alter table "public"."categories" validate constraint "categories_household_id_fkey";

alter table "public"."categories" add constraint "categories_name_key" UNIQUE using index "categories_name_key";

alter table "public"."exceptions" add constraint "exceptions_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.categories(id) not valid;

alter table "public"."exceptions" validate constraint "exceptions_category_id_fkey";

alter table "public"."exceptions" add constraint "exceptions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) not valid;

alter table "public"."exceptions" validate constraint "exceptions_user_id_fkey";

alter table "public"."expenses" add constraint "expenses_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.categories(id) not valid;

alter table "public"."expenses" validate constraint "expenses_category_id_fkey";

alter table "public"."expenses" add constraint "expenses_household_id_fkey" FOREIGN KEY (household_id) REFERENCES public.households(id) not valid;

alter table "public"."expenses" validate constraint "expenses_household_id_fkey";

alter table "public"."household_invites" add constraint "household_invites_household_id_fkey" FOREIGN KEY (household_id) REFERENCES public.households(id) ON DELETE CASCADE not valid;

alter table "public"."household_invites" validate constraint "household_invites_household_id_fkey";

alter table "public"."user_expenses" add constraint "user_expenses_expense_id_fkey" FOREIGN KEY (expense_id) REFERENCES public.expenses(id) not valid;

alter table "public"."user_expenses" validate constraint "user_expenses_expense_id_fkey";

alter table "public"."user_expenses" add constraint "user_expenses_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) not valid;

alter table "public"."user_expenses" validate constraint "user_expenses_user_id_fkey";

alter table "public"."users" add constraint "users_auth_user_id_key" UNIQUE using index "users_auth_user_id_key";

alter table "public"."users" add constraint "users_email_key" UNIQUE using index "users_email_key";

alter table "public"."users" add constraint "users_household_id_fkey" FOREIGN KEY (household_id) REFERENCES public.households(id) not valid;

alter table "public"."users" validate constraint "users_household_id_fkey";

alter table "public"."users" add constraint "users_phone_e164_key" UNIQUE using index "users_phone_e164_key";

grant delete on table "public"."categories" to "anon";

grant insert on table "public"."categories" to "anon";

grant references on table "public"."categories" to "anon";

grant select on table "public"."categories" to "anon";

grant trigger on table "public"."categories" to "anon";

grant truncate on table "public"."categories" to "anon";

grant update on table "public"."categories" to "anon";

grant delete on table "public"."categories" to "authenticated";

grant insert on table "public"."categories" to "authenticated";

grant references on table "public"."categories" to "authenticated";

grant select on table "public"."categories" to "authenticated";

grant trigger on table "public"."categories" to "authenticated";

grant truncate on table "public"."categories" to "authenticated";

grant update on table "public"."categories" to "authenticated";

grant delete on table "public"."categories" to "service_role";

grant insert on table "public"."categories" to "service_role";

grant references on table "public"."categories" to "service_role";

grant select on table "public"."categories" to "service_role";

grant trigger on table "public"."categories" to "service_role";

grant truncate on table "public"."categories" to "service_role";

grant update on table "public"."categories" to "service_role";

grant delete on table "public"."exceptions" to "anon";

grant insert on table "public"."exceptions" to "anon";

grant references on table "public"."exceptions" to "anon";

grant select on table "public"."exceptions" to "anon";

grant trigger on table "public"."exceptions" to "anon";

grant truncate on table "public"."exceptions" to "anon";

grant update on table "public"."exceptions" to "anon";

grant delete on table "public"."exceptions" to "authenticated";

grant insert on table "public"."exceptions" to "authenticated";

grant references on table "public"."exceptions" to "authenticated";

grant select on table "public"."exceptions" to "authenticated";

grant trigger on table "public"."exceptions" to "authenticated";

grant truncate on table "public"."exceptions" to "authenticated";

grant update on table "public"."exceptions" to "authenticated";

grant delete on table "public"."exceptions" to "service_role";

grant insert on table "public"."exceptions" to "service_role";

grant references on table "public"."exceptions" to "service_role";

grant select on table "public"."exceptions" to "service_role";

grant trigger on table "public"."exceptions" to "service_role";

grant truncate on table "public"."exceptions" to "service_role";

grant update on table "public"."exceptions" to "service_role";

grant delete on table "public"."expenses" to "anon";

grant insert on table "public"."expenses" to "anon";

grant references on table "public"."expenses" to "anon";

grant select on table "public"."expenses" to "anon";

grant trigger on table "public"."expenses" to "anon";

grant truncate on table "public"."expenses" to "anon";

grant update on table "public"."expenses" to "anon";

grant delete on table "public"."expenses" to "authenticated";

grant insert on table "public"."expenses" to "authenticated";

grant references on table "public"."expenses" to "authenticated";

grant select on table "public"."expenses" to "authenticated";

grant trigger on table "public"."expenses" to "authenticated";

grant truncate on table "public"."expenses" to "authenticated";

grant update on table "public"."expenses" to "authenticated";

grant delete on table "public"."expenses" to "service_role";

grant insert on table "public"."expenses" to "service_role";

grant references on table "public"."expenses" to "service_role";

grant select on table "public"."expenses" to "service_role";

grant trigger on table "public"."expenses" to "service_role";

grant truncate on table "public"."expenses" to "service_role";

grant update on table "public"."expenses" to "service_role";

grant delete on table "public"."household_invites" to "anon";

grant insert on table "public"."household_invites" to "anon";

grant references on table "public"."household_invites" to "anon";

grant select on table "public"."household_invites" to "anon";

grant trigger on table "public"."household_invites" to "anon";

grant truncate on table "public"."household_invites" to "anon";

grant update on table "public"."household_invites" to "anon";

grant delete on table "public"."household_invites" to "authenticated";

grant insert on table "public"."household_invites" to "authenticated";

grant references on table "public"."household_invites" to "authenticated";

grant select on table "public"."household_invites" to "authenticated";

grant trigger on table "public"."household_invites" to "authenticated";

grant truncate on table "public"."household_invites" to "authenticated";

grant update on table "public"."household_invites" to "authenticated";

grant delete on table "public"."household_invites" to "service_role";

grant insert on table "public"."household_invites" to "service_role";

grant references on table "public"."household_invites" to "service_role";

grant select on table "public"."household_invites" to "service_role";

grant trigger on table "public"."household_invites" to "service_role";

grant truncate on table "public"."household_invites" to "service_role";

grant update on table "public"."household_invites" to "service_role";

grant delete on table "public"."households" to "anon";

grant insert on table "public"."households" to "anon";

grant references on table "public"."households" to "anon";

grant select on table "public"."households" to "anon";

grant trigger on table "public"."households" to "anon";

grant truncate on table "public"."households" to "anon";

grant update on table "public"."households" to "anon";

grant delete on table "public"."households" to "authenticated";

grant insert on table "public"."households" to "authenticated";

grant references on table "public"."households" to "authenticated";

grant select on table "public"."households" to "authenticated";

grant trigger on table "public"."households" to "authenticated";

grant truncate on table "public"."households" to "authenticated";

grant update on table "public"."households" to "authenticated";

grant delete on table "public"."households" to "service_role";

grant insert on table "public"."households" to "service_role";

grant references on table "public"."households" to "service_role";

grant select on table "public"."households" to "service_role";

grant trigger on table "public"."households" to "service_role";

grant truncate on table "public"."households" to "service_role";

grant update on table "public"."households" to "service_role";

grant delete on table "public"."user_expenses" to "anon";

grant insert on table "public"."user_expenses" to "anon";

grant references on table "public"."user_expenses" to "anon";

grant select on table "public"."user_expenses" to "anon";

grant trigger on table "public"."user_expenses" to "anon";

grant truncate on table "public"."user_expenses" to "anon";

grant update on table "public"."user_expenses" to "anon";

grant delete on table "public"."user_expenses" to "authenticated";

grant insert on table "public"."user_expenses" to "authenticated";

grant references on table "public"."user_expenses" to "authenticated";

grant select on table "public"."user_expenses" to "authenticated";

grant trigger on table "public"."user_expenses" to "authenticated";

grant truncate on table "public"."user_expenses" to "authenticated";

grant update on table "public"."user_expenses" to "authenticated";

grant delete on table "public"."user_expenses" to "service_role";

grant insert on table "public"."user_expenses" to "service_role";

grant references on table "public"."user_expenses" to "service_role";

grant select on table "public"."user_expenses" to "service_role";

grant trigger on table "public"."user_expenses" to "service_role";

grant truncate on table "public"."user_expenses" to "service_role";

grant update on table "public"."user_expenses" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";


